# Generated by Django 4.2.2 on 2023-07-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0002_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='parent',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='children', to='posts.todo'),
        ),
    ]
