# Generated by Django 4.2.2 on 2023-07-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_todo_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
    ]
