# Generated by Django 4.2.2 on 2023-07-22 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_todo_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 13, 26, 48, 43910)),
        ),
    ]
