# Generated by Django 4.2.2 on 2023-07-23 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_todo_update_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='todo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 23, 10, 41, 28, 496619)),
        ),
    ]
